"""Initial migration.

Revision ID: e6812b33e759
Revises: 
Create Date: 2022-07-29 18:59:21.787546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6812b33e759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.String(length=30), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priceEach', sa.Float(), nullable=False),
    sa.Column('orderDate', sa.Date(), nullable=False),
    sa.Column('orderStatus', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
